ip: "127.0.0.1"
port: 8089
db:
  host: "localhost"
  port: 5432
  user: "postgres"
  password: "postgres"
  dbname: "mail"
mail_theme_min_len: 3
mail_theme_max_len: 500
mail_text_min_len: 4
mail_text_max_len: 500